### ISSUE TITLE
[Hunt-HighPingChecker.ps1] Throws errors

### ISSUE THREAD

**Issue by gutko** [fscorrupt/Misc-Powershell-Scripts#1]
Check for HuntGame.exe process...
    Found HuntGame.exe with PID: 3192
Running netstat and selecting the ip connected to port beginning with: 610                                                  Found IP:  with Port: , via netstat                                                                                 ########################################################                                                                Your External IP is: xxx.xxx.xx.xxx                                                                                      Your ISP is:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                               ########################################################                                                                Starting tracert now...
WARNING: Trace route to destination fe80::d42a:9f42:60b0:c541%4 did not complete. Trace terminated ::
fe80::d42a:9f42:60b0:c541
Resolve-DnsName : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that
 is not null or empty, and then try the command again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetTCPIP\Test-NetConnection.psm1:313 char:74
+ ... ctionResult.DNSOnlyRecords = @( Resolve-DnsName $ComputerName -DnsOnl ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Resolve-DnsName], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that
 is not null or empty, and then try the command again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetTCPIP\Test-NetConnection.psm1:314 char:79
+ ... Result.LLMNRNetbiosRecords = @( Resolve-DnsName $ComputerName -LlmnrN ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Resolve-DnsName], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.DnsClient.Commands.ResolveDnsName

Resolve-DnsName : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that
 is not null or empty, and then try the command again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetTCPIP\Test-NetConnection.psm1:315 char:78
+ ... nResult.BasicNameResolution = @(Resolve-DnsName $ComputerName -ErrorA ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Resolve-DnsName], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.DnsClient.Commands.ResolveDnsName

    Tracert finished...
Starting Ping measurement...
    Ping is (0ms) and below 100ms for IP: fe80::d42a:9f42:60b0:c541, no further action needed.
        DNS Name is: DESKTOP

Press Enter to continue...:

**Comment by fscorrupt** [comment]
hey, i can see from your errors that you are using ipv6, have not tested this with ipv6.

im trying my best to test this this with ipv6, if you can disable ipv6 on your network card, the script should work.

**Comment by fscorrupt** [comment]
Fixed in latest version
